spring:
  application:
    name: springuser
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_demo
    username: postgres
    password: Yondaime2650
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8083
